apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  replicas: 1
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
      restartPolicy: Always

kind: Service
paiVersion: v1
metadata:
  name: users-service
spec:
  type: NodePort
  ports:
    - port 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: users-service
              