apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  selector:
    matchLabels:
      app: users-service
  replicas: 1
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: spring-boot-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8383
      restartPolicy: Always
----
kind: Service
paiVersion: v1
metadata:
  name: users-service
spec:
  type: NodePort
  ports:
    - port 8383
      targetPort: 8383
      protocol: TCP
      nodePort: 31000
  selector:
    app: users-service
              